build: tema2.cpp HTRoad.h hash.h graph.h hashfunctions.h
	g++ -std=c++11 -Wall -Wextra tema2.cpp -o tema2

O3: tema2.cpp HTRoad.h hash.h graph.h hashfunctions.h
	g++ -std=c++11 -O3 tema2.cpp -o tema2

clean: tema2
	rm -f tema2 task1.out task2.out task3.out
